### ISSUE TITLE
[Helm] Evaluate if it's possible to declare plugin Helm charts as dependencies in the Midaz chart

### ISSUE THREAD

**Issue by ferr3ira-gabriel** [LerianStudio/helm#151]
### Description

To simplify the installation of plugins during client setup and load testing environments, we can declare the Helm charts of the plugins as dependencies in the **Midaz** Helm chart. This approach would be similar to how we currently manage dependencies like PostgreSQL, MongoDB, Valkey, and RabbitMQ.

By including the plugins as chart dependencies, we can control their installation directly via `values.yaml`, making the process more standardized and easier to automate.

### Proposed Structure in `values.yaml`

```yaml
plugin-auth:
  enabled: true
  # remaining values for plugin-auth configuration

plugin-crm:
  enabled: true
  # remaining values for plugin-crm configuration

plugin-smart-templates:
  enabled: true
  # remaining values for plugin-smart-templates configuration
```

### Benefits

* Easier onboarding and setup for new clients.
* Streamlined setup for performance/load testing environments.
* Centralized configuration of all components related to Midaz.

### Next Steps

* Evaluate technical feasibility of adding plugins as dependencies.
* Update the Midaz Helm chart to support optional plugin installation via values.
* Document plugin configuration structure in Midaz’s Helm README.
