### ISSUE TITLE
💡 Configure Deployment Strategy

### ISSUE THREAD

**Issue by guimoreirar** [LerianStudio/helm#85]
### Start Date

03/31/2025

### Summary

The Deployment Strategy in a Kubernetes Deployment Template defines how updates to the deployed pods should be carried out. It controls the manner in which the application is rolled out or rolled back when there is a change in the pod specification, such as a new version of the container image.

### Basic Example

```
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
```

### Drawbacks

Setting high values for maxSurge (e.g., more than 1) or low values for maxUnavailable (e.g., 0) can lead to service interruptions during updates if there aren’t enough resources available to handle both old and new pods simultaneously.
